services:
  db:
    image: postgres:16-alpine
    container_name: course_db
    environment:
      POSTGRES_USER : admin
      POSTGRES_PASSWORD : admin_en
      POSTGRES_DB : swap_db
    ports:
      - "5437:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: