spring.application.name=course-swap

# conexion a PostgreSQL (esta en el contenedor)
spring.datasource.url=jdbc:postgresql://localhost:5437/swap_db
spring.datasource.username=admin
spring.datasource.password=admin_en
spring.datasource.driver-class-name=org.postgresql.Driver
logging.level.org.springframework.security=DEBUG
# hibernate: crea/actualiza las tablas automáticamente segun los @Entity
spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

jwt.secret=NG96NXg4YXRkNG03Y3B3ZTFoOHowbTlsMjA5M3I4NzE=
jwt.expiration=3600000

# dialecto específico para PostgreSQL (opcional en versiones nuevas de Hibernate, pero explícito es mejor)
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.defer-datasource-initialization=true
#spring.sql.init.mode=always
